// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: paktoken/tokenization/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "paktoken.tokenization.v1";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (defaults to x/gov unless overwritten). */
  authority: string;
  /** NOTE: All parameters must be supplied. */
  params: Params | undefined;
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {
}

/** MsgCreateProject defines the MsgCreateProject message. */
export interface MsgCreateProject {
  creator: string;
  name: string;
  totalSupply: string;
  owner: string;
  tokenPrice: number;
}

/** MsgCreateProjectResponse defines the MsgCreateProjectResponse message. */
export interface MsgCreateProjectResponse {
  id: number;
}

/** MsgUpdateProject defines the MsgUpdateProject message. */
export interface MsgUpdateProject {
  creator: string;
  id: number;
  name: string;
  totalSupply: string;
  owner: string;
  tokenPrice: number;
}

/** MsgUpdateProjectResponse defines the MsgUpdateProjectResponse message. */
export interface MsgUpdateProjectResponse {
}

/** MsgDeleteProject defines the MsgDeleteProject message. */
export interface MsgDeleteProject {
  creator: string;
  id: number;
}

/** MsgDeleteProjectResponse defines the MsgDeleteProjectResponse message. */
export interface MsgDeleteProjectResponse {
}

/** MsgBuyTokens defines the MsgBuyTokens message. */
export interface MsgBuyTokens {
  creator: string;
  projectId: number;
  amount: number;
}

/** MsgBuyTokensResponse defines the MsgBuyTokensResponse message. */
export interface MsgBuyTokensResponse {
}

/** MsgDistributeRevenue defines the MsgDistributeRevenue message. */
export interface MsgDistributeRevenue {
  creator: string;
  projectId: number;
  amount: number;
}

/** MsgDistributeRevenueResponse defines the MsgDistributeRevenueResponse message. */
export interface MsgDistributeRevenueResponse {
}

/** MsgCreateHolding defines the MsgCreateHolding message. */
export interface MsgCreateHolding {
  creator: string;
  index: string;
  amount: number;
  projectId: number;
  investor: string;
}

/** MsgCreateHoldingResponse defines the MsgCreateHoldingResponse message. */
export interface MsgCreateHoldingResponse {
}

/** MsgUpdateHolding defines the MsgUpdateHolding message. */
export interface MsgUpdateHolding {
  creator: string;
  index: string;
  amount: number;
  projectId: number;
  investor: string;
}

/** MsgUpdateHoldingResponse defines the MsgUpdateHoldingResponse message. */
export interface MsgUpdateHoldingResponse {
}

/** MsgDeleteHolding defines the MsgDeleteHolding message. */
export interface MsgDeleteHolding {
  creator: string;
  index: string;
}

/** MsgDeleteHoldingResponse defines the MsgDeleteHoldingResponse message. */
export interface MsgDeleteHoldingResponse {
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgUpdateParams();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.authority = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.params = Params.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgUpdateParamsResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgCreateProject(): MsgCreateProject {
  return { creator: "", name: "", totalSupply: "", owner: "", tokenPrice: 0 };
}

export const MsgCreateProject: MessageFns<MsgCreateProject> = {
  encode(message: MsgCreateProject, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.totalSupply !== "") {
      writer.uint32(26).string(message.totalSupply);
    }
    if (message.owner !== "") {
      writer.uint32(34).string(message.owner);
    }
    if (message.tokenPrice !== 0) {
      writer.uint32(40).uint64(message.tokenPrice);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateProject {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgCreateProject();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.creator = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.name = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.totalSupply = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.owner = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.tokenPrice = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgCreateProject {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      totalSupply: isSet(object.totalSupply)
        ? globalThis.String(object.totalSupply)
        : isSet(object.total_supply)
        ? globalThis.String(object.total_supply)
        : "",
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      tokenPrice: isSet(object.tokenPrice)
        ? globalThis.Number(object.tokenPrice)
        : isSet(object.token_price)
        ? globalThis.Number(object.token_price)
        : 0,
    };
  },

  toJSON(message: MsgCreateProject): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.totalSupply !== "") {
      obj.totalSupply = message.totalSupply;
    }
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.tokenPrice !== 0) {
      obj.tokenPrice = Math.round(message.tokenPrice);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateProject>, I>>(base?: I): MsgCreateProject {
    return MsgCreateProject.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateProject>, I>>(object: I): MsgCreateProject {
    const message = createBaseMsgCreateProject();
    message.creator = object.creator ?? "";
    message.name = object.name ?? "";
    message.totalSupply = object.totalSupply ?? "";
    message.owner = object.owner ?? "";
    message.tokenPrice = object.tokenPrice ?? 0;
    return message;
  },
};

function createBaseMsgCreateProjectResponse(): MsgCreateProjectResponse {
  return { id: 0 };
}

export const MsgCreateProjectResponse: MessageFns<MsgCreateProjectResponse> = {
  encode(message: MsgCreateProjectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateProjectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgCreateProjectResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.id = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgCreateProjectResponse {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: MsgCreateProjectResponse): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateProjectResponse>, I>>(base?: I): MsgCreateProjectResponse {
    return MsgCreateProjectResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateProjectResponse>, I>>(object: I): MsgCreateProjectResponse {
    const message = createBaseMsgCreateProjectResponse();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseMsgUpdateProject(): MsgUpdateProject {
  return { creator: "", id: 0, name: "", totalSupply: "", owner: "", tokenPrice: 0 };
}

export const MsgUpdateProject: MessageFns<MsgUpdateProject> = {
  encode(message: MsgUpdateProject, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.id !== 0) {
      writer.uint32(16).uint64(message.id);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.totalSupply !== "") {
      writer.uint32(34).string(message.totalSupply);
    }
    if (message.owner !== "") {
      writer.uint32(42).string(message.owner);
    }
    if (message.tokenPrice !== 0) {
      writer.uint32(48).uint64(message.tokenPrice);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateProject {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgUpdateProject();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.creator = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.id = longToNumber(reader.uint64());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.name = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.totalSupply = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.owner = reader.string();
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.tokenPrice = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgUpdateProject {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      totalSupply: isSet(object.totalSupply)
        ? globalThis.String(object.totalSupply)
        : isSet(object.total_supply)
        ? globalThis.String(object.total_supply)
        : "",
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      tokenPrice: isSet(object.tokenPrice)
        ? globalThis.Number(object.tokenPrice)
        : isSet(object.token_price)
        ? globalThis.Number(object.token_price)
        : 0,
    };
  },

  toJSON(message: MsgUpdateProject): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.totalSupply !== "") {
      obj.totalSupply = message.totalSupply;
    }
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.tokenPrice !== 0) {
      obj.tokenPrice = Math.round(message.tokenPrice);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateProject>, I>>(base?: I): MsgUpdateProject {
    return MsgUpdateProject.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateProject>, I>>(object: I): MsgUpdateProject {
    const message = createBaseMsgUpdateProject();
    message.creator = object.creator ?? "";
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.totalSupply = object.totalSupply ?? "";
    message.owner = object.owner ?? "";
    message.tokenPrice = object.tokenPrice ?? 0;
    return message;
  },
};

function createBaseMsgUpdateProjectResponse(): MsgUpdateProjectResponse {
  return {};
}

export const MsgUpdateProjectResponse: MessageFns<MsgUpdateProjectResponse> = {
  encode(_: MsgUpdateProjectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateProjectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgUpdateProjectResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): MsgUpdateProjectResponse {
    return {};
  },

  toJSON(_: MsgUpdateProjectResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateProjectResponse>, I>>(base?: I): MsgUpdateProjectResponse {
    return MsgUpdateProjectResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateProjectResponse>, I>>(_: I): MsgUpdateProjectResponse {
    const message = createBaseMsgUpdateProjectResponse();
    return message;
  },
};

function createBaseMsgDeleteProject(): MsgDeleteProject {
  return { creator: "", id: 0 };
}

export const MsgDeleteProject: MessageFns<MsgDeleteProject> = {
  encode(message: MsgDeleteProject, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.id !== 0) {
      writer.uint32(16).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDeleteProject {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgDeleteProject();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.creator = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.id = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgDeleteProject {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
    };
  },

  toJSON(message: MsgDeleteProject): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDeleteProject>, I>>(base?: I): MsgDeleteProject {
    return MsgDeleteProject.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDeleteProject>, I>>(object: I): MsgDeleteProject {
    const message = createBaseMsgDeleteProject();
    message.creator = object.creator ?? "";
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseMsgDeleteProjectResponse(): MsgDeleteProjectResponse {
  return {};
}

export const MsgDeleteProjectResponse: MessageFns<MsgDeleteProjectResponse> = {
  encode(_: MsgDeleteProjectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDeleteProjectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgDeleteProjectResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): MsgDeleteProjectResponse {
    return {};
  },

  toJSON(_: MsgDeleteProjectResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDeleteProjectResponse>, I>>(base?: I): MsgDeleteProjectResponse {
    return MsgDeleteProjectResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDeleteProjectResponse>, I>>(_: I): MsgDeleteProjectResponse {
    const message = createBaseMsgDeleteProjectResponse();
    return message;
  },
};

function createBaseMsgBuyTokens(): MsgBuyTokens {
  return { creator: "", projectId: 0, amount: 0 };
}

export const MsgBuyTokens: MessageFns<MsgBuyTokens> = {
  encode(message: MsgBuyTokens, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.projectId !== 0) {
      writer.uint32(16).uint64(message.projectId);
    }
    if (message.amount !== 0) {
      writer.uint32(24).uint64(message.amount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgBuyTokens {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgBuyTokens();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.creator = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.projectId = longToNumber(reader.uint64());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.amount = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgBuyTokens {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      projectId: isSet(object.projectId)
        ? globalThis.Number(object.projectId)
        : isSet(object.project_id)
        ? globalThis.Number(object.project_id)
        : 0,
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
    };
  },

  toJSON(message: MsgBuyTokens): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.projectId !== 0) {
      obj.projectId = Math.round(message.projectId);
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgBuyTokens>, I>>(base?: I): MsgBuyTokens {
    return MsgBuyTokens.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgBuyTokens>, I>>(object: I): MsgBuyTokens {
    const message = createBaseMsgBuyTokens();
    message.creator = object.creator ?? "";
    message.projectId = object.projectId ?? 0;
    message.amount = object.amount ?? 0;
    return message;
  },
};

function createBaseMsgBuyTokensResponse(): MsgBuyTokensResponse {
  return {};
}

export const MsgBuyTokensResponse: MessageFns<MsgBuyTokensResponse> = {
  encode(_: MsgBuyTokensResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgBuyTokensResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgBuyTokensResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): MsgBuyTokensResponse {
    return {};
  },

  toJSON(_: MsgBuyTokensResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgBuyTokensResponse>, I>>(base?: I): MsgBuyTokensResponse {
    return MsgBuyTokensResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgBuyTokensResponse>, I>>(_: I): MsgBuyTokensResponse {
    const message = createBaseMsgBuyTokensResponse();
    return message;
  },
};

function createBaseMsgDistributeRevenue(): MsgDistributeRevenue {
  return { creator: "", projectId: 0, amount: 0 };
}

export const MsgDistributeRevenue: MessageFns<MsgDistributeRevenue> = {
  encode(message: MsgDistributeRevenue, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.projectId !== 0) {
      writer.uint32(16).uint64(message.projectId);
    }
    if (message.amount !== 0) {
      writer.uint32(24).uint64(message.amount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDistributeRevenue {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgDistributeRevenue();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.creator = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.projectId = longToNumber(reader.uint64());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.amount = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgDistributeRevenue {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      projectId: isSet(object.projectId)
        ? globalThis.Number(object.projectId)
        : isSet(object.project_id)
        ? globalThis.Number(object.project_id)
        : 0,
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
    };
  },

  toJSON(message: MsgDistributeRevenue): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.projectId !== 0) {
      obj.projectId = Math.round(message.projectId);
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDistributeRevenue>, I>>(base?: I): MsgDistributeRevenue {
    return MsgDistributeRevenue.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDistributeRevenue>, I>>(object: I): MsgDistributeRevenue {
    const message = createBaseMsgDistributeRevenue();
    message.creator = object.creator ?? "";
    message.projectId = object.projectId ?? 0;
    message.amount = object.amount ?? 0;
    return message;
  },
};

function createBaseMsgDistributeRevenueResponse(): MsgDistributeRevenueResponse {
  return {};
}

export const MsgDistributeRevenueResponse: MessageFns<MsgDistributeRevenueResponse> = {
  encode(_: MsgDistributeRevenueResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDistributeRevenueResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgDistributeRevenueResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): MsgDistributeRevenueResponse {
    return {};
  },

  toJSON(_: MsgDistributeRevenueResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDistributeRevenueResponse>, I>>(base?: I): MsgDistributeRevenueResponse {
    return MsgDistributeRevenueResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDistributeRevenueResponse>, I>>(_: I): MsgDistributeRevenueResponse {
    const message = createBaseMsgDistributeRevenueResponse();
    return message;
  },
};

function createBaseMsgCreateHolding(): MsgCreateHolding {
  return { creator: "", index: "", amount: 0, projectId: 0, investor: "" };
}

export const MsgCreateHolding: MessageFns<MsgCreateHolding> = {
  encode(message: MsgCreateHolding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.index !== "") {
      writer.uint32(18).string(message.index);
    }
    if (message.amount !== 0) {
      writer.uint32(24).uint64(message.amount);
    }
    if (message.projectId !== 0) {
      writer.uint32(32).uint64(message.projectId);
    }
    if (message.investor !== "") {
      writer.uint32(42).string(message.investor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateHolding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgCreateHolding();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.creator = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.index = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.amount = longToNumber(reader.uint64());
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.projectId = longToNumber(reader.uint64());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.investor = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgCreateHolding {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      index: isSet(object.index) ? globalThis.String(object.index) : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      projectId: isSet(object.projectId)
        ? globalThis.Number(object.projectId)
        : isSet(object.project_id)
        ? globalThis.Number(object.project_id)
        : 0,
      investor: isSet(object.investor) ? globalThis.String(object.investor) : "",
    };
  },

  toJSON(message: MsgCreateHolding): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.index !== "") {
      obj.index = message.index;
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    if (message.projectId !== 0) {
      obj.projectId = Math.round(message.projectId);
    }
    if (message.investor !== "") {
      obj.investor = message.investor;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateHolding>, I>>(base?: I): MsgCreateHolding {
    return MsgCreateHolding.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateHolding>, I>>(object: I): MsgCreateHolding {
    const message = createBaseMsgCreateHolding();
    message.creator = object.creator ?? "";
    message.index = object.index ?? "";
    message.amount = object.amount ?? 0;
    message.projectId = object.projectId ?? 0;
    message.investor = object.investor ?? "";
    return message;
  },
};

function createBaseMsgCreateHoldingResponse(): MsgCreateHoldingResponse {
  return {};
}

export const MsgCreateHoldingResponse: MessageFns<MsgCreateHoldingResponse> = {
  encode(_: MsgCreateHoldingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateHoldingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgCreateHoldingResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): MsgCreateHoldingResponse {
    return {};
  },

  toJSON(_: MsgCreateHoldingResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateHoldingResponse>, I>>(base?: I): MsgCreateHoldingResponse {
    return MsgCreateHoldingResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateHoldingResponse>, I>>(_: I): MsgCreateHoldingResponse {
    const message = createBaseMsgCreateHoldingResponse();
    return message;
  },
};

function createBaseMsgUpdateHolding(): MsgUpdateHolding {
  return { creator: "", index: "", amount: 0, projectId: 0, investor: "" };
}

export const MsgUpdateHolding: MessageFns<MsgUpdateHolding> = {
  encode(message: MsgUpdateHolding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.index !== "") {
      writer.uint32(18).string(message.index);
    }
    if (message.amount !== 0) {
      writer.uint32(24).uint64(message.amount);
    }
    if (message.projectId !== 0) {
      writer.uint32(32).uint64(message.projectId);
    }
    if (message.investor !== "") {
      writer.uint32(42).string(message.investor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateHolding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgUpdateHolding();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.creator = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.index = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.amount = longToNumber(reader.uint64());
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.projectId = longToNumber(reader.uint64());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.investor = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgUpdateHolding {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      index: isSet(object.index) ? globalThis.String(object.index) : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      projectId: isSet(object.projectId)
        ? globalThis.Number(object.projectId)
        : isSet(object.project_id)
        ? globalThis.Number(object.project_id)
        : 0,
      investor: isSet(object.investor) ? globalThis.String(object.investor) : "",
    };
  },

  toJSON(message: MsgUpdateHolding): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.index !== "") {
      obj.index = message.index;
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    if (message.projectId !== 0) {
      obj.projectId = Math.round(message.projectId);
    }
    if (message.investor !== "") {
      obj.investor = message.investor;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateHolding>, I>>(base?: I): MsgUpdateHolding {
    return MsgUpdateHolding.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateHolding>, I>>(object: I): MsgUpdateHolding {
    const message = createBaseMsgUpdateHolding();
    message.creator = object.creator ?? "";
    message.index = object.index ?? "";
    message.amount = object.amount ?? 0;
    message.projectId = object.projectId ?? 0;
    message.investor = object.investor ?? "";
    return message;
  },
};

function createBaseMsgUpdateHoldingResponse(): MsgUpdateHoldingResponse {
  return {};
}

export const MsgUpdateHoldingResponse: MessageFns<MsgUpdateHoldingResponse> = {
  encode(_: MsgUpdateHoldingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateHoldingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgUpdateHoldingResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): MsgUpdateHoldingResponse {
    return {};
  },

  toJSON(_: MsgUpdateHoldingResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateHoldingResponse>, I>>(base?: I): MsgUpdateHoldingResponse {
    return MsgUpdateHoldingResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateHoldingResponse>, I>>(_: I): MsgUpdateHoldingResponse {
    const message = createBaseMsgUpdateHoldingResponse();
    return message;
  },
};

function createBaseMsgDeleteHolding(): MsgDeleteHolding {
  return { creator: "", index: "" };
}

export const MsgDeleteHolding: MessageFns<MsgDeleteHolding> = {
  encode(message: MsgDeleteHolding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.index !== "") {
      writer.uint32(18).string(message.index);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDeleteHolding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgDeleteHolding();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.creator = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.index = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgDeleteHolding {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      index: isSet(object.index) ? globalThis.String(object.index) : "",
    };
  },

  toJSON(message: MsgDeleteHolding): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.index !== "") {
      obj.index = message.index;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDeleteHolding>, I>>(base?: I): MsgDeleteHolding {
    return MsgDeleteHolding.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDeleteHolding>, I>>(object: I): MsgDeleteHolding {
    const message = createBaseMsgDeleteHolding();
    message.creator = object.creator ?? "";
    message.index = object.index ?? "";
    return message;
  },
};

function createBaseMsgDeleteHoldingResponse(): MsgDeleteHoldingResponse {
  return {};
}

export const MsgDeleteHoldingResponse: MessageFns<MsgDeleteHoldingResponse> = {
  encode(_: MsgDeleteHoldingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDeleteHoldingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgDeleteHoldingResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): MsgDeleteHoldingResponse {
    return {};
  },

  toJSON(_: MsgDeleteHoldingResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDeleteHoldingResponse>, I>>(base?: I): MsgDeleteHoldingResponse {
    return MsgDeleteHoldingResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDeleteHoldingResponse>, I>>(_: I): MsgDeleteHoldingResponse {
    const message = createBaseMsgDeleteHoldingResponse();
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  /** CreateProject defines the CreateProject RPC. */
  CreateProject(request: MsgCreateProject): Promise<MsgCreateProjectResponse>;
  /** UpdateProject defines the UpdateProject RPC. */
  UpdateProject(request: MsgUpdateProject): Promise<MsgUpdateProjectResponse>;
  /** DeleteProject defines the DeleteProject RPC. */
  DeleteProject(request: MsgDeleteProject): Promise<MsgDeleteProjectResponse>;
  /** BuyTokens defines the BuyTokens RPC. */
  BuyTokens(request: MsgBuyTokens): Promise<MsgBuyTokensResponse>;
  /** DistributeRevenue defines the DistributeRevenue RPC. */
  DistributeRevenue(request: MsgDistributeRevenue): Promise<MsgDistributeRevenueResponse>;
  /** CreateHolding defines the CreateHolding RPC. */
  CreateHolding(request: MsgCreateHolding): Promise<MsgCreateHoldingResponse>;
  /** UpdateHolding defines the UpdateHolding RPC. */
  UpdateHolding(request: MsgUpdateHolding): Promise<MsgUpdateHoldingResponse>;
  /** DeleteHolding defines the DeleteHolding RPC. */
  DeleteHolding(request: MsgDeleteHolding): Promise<MsgDeleteHoldingResponse>;
}

export const MsgServiceName = "paktoken.tokenization.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.CreateProject = this.CreateProject.bind(this);
    this.UpdateProject = this.UpdateProject.bind(this);
    this.DeleteProject = this.DeleteProject.bind(this);
    this.BuyTokens = this.BuyTokens.bind(this);
    this.DistributeRevenue = this.DistributeRevenue.bind(this);
    this.CreateHolding = this.CreateHolding.bind(this);
    this.UpdateHolding = this.UpdateHolding.bind(this);
    this.DeleteHolding = this.DeleteHolding.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  CreateProject(request: MsgCreateProject): Promise<MsgCreateProjectResponse> {
    const data = MsgCreateProject.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateProject", data);
    return promise.then((data) => MsgCreateProjectResponse.decode(new BinaryReader(data)));
  }

  UpdateProject(request: MsgUpdateProject): Promise<MsgUpdateProjectResponse> {
    const data = MsgUpdateProject.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateProject", data);
    return promise.then((data) => MsgUpdateProjectResponse.decode(new BinaryReader(data)));
  }

  DeleteProject(request: MsgDeleteProject): Promise<MsgDeleteProjectResponse> {
    const data = MsgDeleteProject.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteProject", data);
    return promise.then((data) => MsgDeleteProjectResponse.decode(new BinaryReader(data)));
  }

  BuyTokens(request: MsgBuyTokens): Promise<MsgBuyTokensResponse> {
    const data = MsgBuyTokens.encode(request).finish();
    const promise = this.rpc.request(this.service, "BuyTokens", data);
    return promise.then((data) => MsgBuyTokensResponse.decode(new BinaryReader(data)));
  }

  DistributeRevenue(request: MsgDistributeRevenue): Promise<MsgDistributeRevenueResponse> {
    const data = MsgDistributeRevenue.encode(request).finish();
    const promise = this.rpc.request(this.service, "DistributeRevenue", data);
    return promise.then((data) => MsgDistributeRevenueResponse.decode(new BinaryReader(data)));
  }

  CreateHolding(request: MsgCreateHolding): Promise<MsgCreateHoldingResponse> {
    const data = MsgCreateHolding.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateHolding", data);
    return promise.then((data) => MsgCreateHoldingResponse.decode(new BinaryReader(data)));
  }

  UpdateHolding(request: MsgUpdateHolding): Promise<MsgUpdateHoldingResponse> {
    const data = MsgUpdateHolding.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateHolding", data);
    return promise.then((data) => MsgUpdateHoldingResponse.decode(new BinaryReader(data)));
  }

  DeleteHolding(request: MsgDeleteHolding): Promise<MsgDeleteHoldingResponse> {
    const data = MsgDeleteHolding.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteHolding", data);
    return promise.then((data) => MsgDeleteHoldingResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
