// Generated by Ignite ignite.com/cli

import { SigningStargateClient, DeliverTxResponse, StdFee } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgUpdateParams } from "./types/paktoken/tokenization/v1/tx";
import { MsgCreateProject } from "./types/paktoken/tokenization/v1/tx";
import { MsgUpdateProject } from "./types/paktoken/tokenization/v1/tx";
import { MsgDeleteProject } from "./types/paktoken/tokenization/v1/tx";
import { MsgBuyTokens } from "./types/paktoken/tokenization/v1/tx";
import { MsgDistributeRevenue } from "./types/paktoken/tokenization/v1/tx";
import { MsgCreateHolding } from "./types/paktoken/tokenization/v1/tx";
import { MsgUpdateHolding } from "./types/paktoken/tokenization/v1/tx";
import { MsgDeleteHolding } from "./types/paktoken/tokenization/v1/tx";

import { Holding as typeHolding} from "./types"
import { Params as typeParams} from "./types"
import { Project as typeProject} from "./types"

export { MsgUpdateParams, MsgCreateProject, MsgUpdateProject, MsgDeleteProject, MsgBuyTokens, MsgDistributeRevenue, MsgCreateHolding, MsgUpdateHolding, MsgDeleteHolding };

type sendMsgUpdateParamsParams = {
  value: MsgUpdateParams,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateProjectParams = {
  value: MsgCreateProject,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateProjectParams = {
  value: MsgUpdateProject,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteProjectParams = {
  value: MsgDeleteProject,
  fee?: StdFee,
  memo?: string
};

type sendMsgBuyTokensParams = {
  value: MsgBuyTokens,
  fee?: StdFee,
  memo?: string
};

type sendMsgDistributeRevenueParams = {
  value: MsgDistributeRevenue,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateHoldingParams = {
  value: MsgCreateHolding,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateHoldingParams = {
  value: MsgUpdateHolding,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteHoldingParams = {
  value: MsgDeleteHolding,
  fee?: StdFee,
  memo?: string
};


type msgUpdateParamsParams = {
  value: MsgUpdateParams,
};

type msgCreateProjectParams = {
  value: MsgCreateProject,
};

type msgUpdateProjectParams = {
  value: MsgUpdateProject,
};

type msgDeleteProjectParams = {
  value: MsgDeleteProject,
};

type msgBuyTokensParams = {
  value: MsgBuyTokens,
};

type msgDistributeRevenueParams = {
  value: MsgDistributeRevenue,
};

type msgCreateHoldingParams = {
  value: MsgCreateHolding,
};

type msgUpdateHoldingParams = {
  value: MsgUpdateHolding,
};

type msgDeleteHoldingParams = {
  value: MsgDeleteHolding,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgUpdateParams({ value, fee, memo }: sendMsgUpdateParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateProject({ value, fee, memo }: sendMsgCreateProjectParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateProject: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgCreateProject({ value: MsgCreateProject.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateProject: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateProject({ value, fee, memo }: sendMsgUpdateProjectParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateProject: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateProject({ value: MsgUpdateProject.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateProject: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeleteProject({ value, fee, memo }: sendMsgDeleteProjectParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeleteProject: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgDeleteProject({ value: MsgDeleteProject.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeleteProject: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgBuyTokens({ value, fee, memo }: sendMsgBuyTokensParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgBuyTokens: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgBuyTokens({ value: MsgBuyTokens.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgBuyTokens: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDistributeRevenue({ value, fee, memo }: sendMsgDistributeRevenueParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDistributeRevenue: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgDistributeRevenue({ value: MsgDistributeRevenue.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDistributeRevenue: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateHolding({ value, fee, memo }: sendMsgCreateHoldingParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateHolding: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgCreateHolding({ value: MsgCreateHolding.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateHolding: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateHolding({ value, fee, memo }: sendMsgUpdateHoldingParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateHolding: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateHolding({ value: MsgUpdateHolding.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateHolding: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeleteHolding({ value, fee, memo }: sendMsgDeleteHoldingParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeleteHolding: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgDeleteHolding({ value: MsgDeleteHolding.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeleteHolding: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgUpdateParams({ value }: msgUpdateParamsParams): EncodeObject {
			try {
				return { typeUrl: "/paktoken.tokenization.v1.MsgUpdateParams", value: MsgUpdateParams.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message)
			}
		},
		
		msgCreateProject({ value }: msgCreateProjectParams): EncodeObject {
			try {
				return { typeUrl: "/paktoken.tokenization.v1.MsgCreateProject", value: MsgCreateProject.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateProject: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateProject({ value }: msgUpdateProjectParams): EncodeObject {
			try {
				return { typeUrl: "/paktoken.tokenization.v1.MsgUpdateProject", value: MsgUpdateProject.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateProject: Could not create message: ' + e.message)
			}
		},
		
		msgDeleteProject({ value }: msgDeleteProjectParams): EncodeObject {
			try {
				return { typeUrl: "/paktoken.tokenization.v1.MsgDeleteProject", value: MsgDeleteProject.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeleteProject: Could not create message: ' + e.message)
			}
		},
		
		msgBuyTokens({ value }: msgBuyTokensParams): EncodeObject {
			try {
				return { typeUrl: "/paktoken.tokenization.v1.MsgBuyTokens", value: MsgBuyTokens.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgBuyTokens: Could not create message: ' + e.message)
			}
		},
		
		msgDistributeRevenue({ value }: msgDistributeRevenueParams): EncodeObject {
			try {
				return { typeUrl: "/paktoken.tokenization.v1.MsgDistributeRevenue", value: MsgDistributeRevenue.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDistributeRevenue: Could not create message: ' + e.message)
			}
		},
		
		msgCreateHolding({ value }: msgCreateHoldingParams): EncodeObject {
			try {
				return { typeUrl: "/paktoken.tokenization.v1.MsgCreateHolding", value: MsgCreateHolding.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateHolding: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateHolding({ value }: msgUpdateHoldingParams): EncodeObject {
			try {
				return { typeUrl: "/paktoken.tokenization.v1.MsgUpdateHolding", value: MsgUpdateHolding.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateHolding: Could not create message: ' + e.message)
			}
		},
		
		msgDeleteHolding({ value }: msgDeleteHoldingParams): EncodeObject {
			try {
				return { typeUrl: "/paktoken.tokenization.v1.MsgDeleteHolding", value: MsgDeleteHolding.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeleteHolding: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Holding: getStructure(typeHolding.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						Project: getStructure(typeProject.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const IgntModule = (test: IgniteClient) => {
	return {
		module: {
			PaktokenTokenizationV_1: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default IgntModule;